#!/bin/bash
set -e

# Protohost Deploy - Installation Script
# This script installs protohost-deploy into an existing project

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_DIR="${1:-.}"

echo "🚀 Installing protohost-deploy..."
echo ""

# Ensure we're in a valid project directory
if [ ! -d "$PROJECT_DIR" ]; then
    echo "❌ Error: Directory '$PROJECT_DIR' does not exist"
    exit 1
fi

cd "$PROJECT_DIR"
PROJECT_DIR="$(pwd)"

echo "📁 Project directory: $PROJECT_DIR"
echo ""

# Check for docker-compose.yml
if [ ! -f "docker-compose.yml" ]; then
    echo "⚠️  Warning: No docker-compose.yml found in project root"
    read -p "Continue anyway? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

# Create .protohost directory
echo "📦 Creating .protohost directory..."
mkdir -p .protohost/{bin,lib}

# Create symlinks to protohost-deploy scripts
echo "🔗 Creating symlinks to protohost-deploy..."
ln -sf "$SCRIPT_DIR/lib/deploy.sh" .protohost/lib/deploy.sh
ln -sf "$SCRIPT_DIR/lib/get_ports.py" .protohost/lib/get_ports.py
ln -sf "$SCRIPT_DIR/lib/list_deployments.sh" .protohost/lib/list_deployments.sh
ln -sf "$SCRIPT_DIR/lib/nginx_manage.sh" .protohost/lib/nginx_manage.sh

# Create .protohost.config if it doesn't exist
if [ ! -f ".protohost.config" ]; then
    echo "⚙️  Creating .protohost.config..."

    # Try to detect git remote URL
    DETECTED_REPO_URL=""
    if [ -d ".git" ]; then
        DETECTED_REPO_URL=$(git config --get remote.origin.url 2>/dev/null || echo "")
    fi

    # Detect current git branch
    DETECTED_BRANCH="main"
    if [ -d ".git" ]; then
        DETECTED_BRANCH=$(git branch --show-current 2>/dev/null || echo "main")
    fi

    # Try to infer project name from directory
    PROJECT_NAME=$(basename "$PROJECT_DIR" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g')

    cat > .protohost.config <<EOF
# Protohost Deploy Configuration
# Generated by install.sh on $(date)

# Remote server configuration
REMOTE_HOST="protohost.xyz"
REMOTE_USER="\${USER}"
REMOTE_BASE_DIR="~/protohost"

# Network configuration
# NGINX_PROXY_HOST: IP address where Docker containers are running
# NGINX_SERVER: IP address where nginx is running (can be same or different)
NGINX_PROXY_HOST="10.10.20.4"
NGINX_SERVER="10.10.20.10"

# Project configuration
PROJECT_PREFIX="$PROJECT_NAME"

# Git repository
REPO_URL="${DETECTED_REPO_URL:-git@github.com:YOUR_ORG/YOUR_REPO.git}"

# Deployment settings
TTL_DAYS=7  # Days until deployment auto-expires

# Optional: Custom port ranges (defaults shown)
# BASE_WEB_PORT=3000
# BASE_MYSQL_PORT=3306
# BASE_REDIS_PORT=6379
EOF

    echo "✓ Created .protohost.config"
    echo ""
    echo "⚠️  Please review and update .protohost.config with your settings:"
    echo "   - REMOTE_HOST: Your protohost server hostname"
    echo "   - REMOTE_USER: Your SSH username"
    echo "   - NGINX_PROXY_HOST: IP where Docker is running"
    echo "   - NGINX_SERVER: IP where nginx is running"
    echo "   - PROJECT_PREFIX: Short name for your project"
    echo "   - REPO_URL: Your git repository URL"
    echo ""
else
    echo "✓ .protohost.config already exists (keeping existing)"
fi

# Add protohost targets to Makefile or create one
if [ -f "Makefile" ]; then
    # Check if protohost targets already exist
    if grep -q "# PROTOHOST-DEPLOY-TARGETS" Makefile; then
        echo "✓ Makefile already has protohost targets"
    else
        echo "📝 Adding protohost targets to existing Makefile..."
        cat >> Makefile <<'EOF'

# PROTOHOST-DEPLOY-TARGETS
# Auto-generated by protohost-deploy - do not edit this section manually
include .protohost/Makefile.inc
EOF
        echo "✓ Updated Makefile"
    fi
else
    echo "📝 Creating new Makefile with protohost targets..."
    cp "$SCRIPT_DIR/templates/Makefile.template" Makefile
    echo "✓ Created Makefile"
fi

# Create the Makefile.inc that will be included
echo "📝 Creating .protohost/Makefile.inc..."
cat > .protohost/Makefile.inc <<'EOF'
# Protohost Deploy - Makefile Include
# This file is auto-generated - do not edit manually

# Load configuration
include .protohost.config

# Detect current branch
BRANCH := $(shell git branch --show-current 2>/dev/null || echo "main")
PROJECT_NAME := $(PROJECT_PREFIX)-$(BRANCH)

# Get dynamic ports from script
PORTS := $(shell python3 .protohost/lib/get_ports.py $(PROJECT_NAME))
WEB_PORT := $(word 1, $(PORTS))
MYSQL_PORT := $(word 2, $(PORTS))
REDIS_PORT := $(word 3, $(PORTS))

.PHONY: up down logs info restart list-all nginx-config nginx-enable nginx-disable nginx-list deploy

up:
	@echo "Starting environment for project '$(PROJECT_NAME)'"
	@echo "  Web: http://localhost:$(WEB_PORT)"
	@echo "  MySQL: $(MYSQL_PORT)"
	@echo "  Redis: $(REDIS_PORT)"
	WEB_PORT=$(WEB_PORT) MYSQL_PORT=$(MYSQL_PORT) REDIS_PORT=$(REDIS_PORT) docker compose -p $(PROJECT_NAME) up -d --wait
	@mkdir -p $(REMOTE_BASE_DIR)/.ports
	@echo "WEB_PORT=$(WEB_PORT)" > $(REMOTE_BASE_DIR)/.ports/$(PROJECT_NAME)
	@echo "MYSQL_PORT=$(MYSQL_PORT)" >> $(REMOTE_BASE_DIR)/.ports/$(PROJECT_NAME)
	@echo "REDIS_PORT=$(REDIS_PORT)" >> $(REMOTE_BASE_DIR)/.ports/$(PROJECT_NAME)
	@echo "BRANCH=$(BRANCH)" >> $(REMOTE_BASE_DIR)/.ports/$(PROJECT_NAME)
	@echo "CREATED=$$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $(REMOTE_BASE_DIR)/.ports/$(PROJECT_NAME)
	@echo "EXPIRES=$$(date -u -d '+$(TTL_DAYS) days' +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || date -u -v+$(TTL_DAYS)d +%Y-%m-%dT%H:%M:%SZ)" >> $(REMOTE_BASE_DIR)/.ports/$(PROJECT_NAME)

down:
	docker compose -p $(PROJECT_NAME) down
	@rm -f $(REMOTE_BASE_DIR)/.ports/$(PROJECT_NAME)
	@rm -f $(REMOTE_BASE_DIR)/.nginx/$(PROJECT_NAME).conf

restart:
	WEB_PORT=$(WEB_PORT) MYSQL_PORT=$(MYSQL_PORT) REDIS_PORT=$(REDIS_PORT) docker compose -p $(PROJECT_NAME) restart

logs:
	docker compose -p $(PROJECT_NAME) logs -f

info:
	@echo "Environment Info:"
	@echo "  Branch:  $(BRANCH)"
	@echo "  Project: $(PROJECT_NAME)"
	@if [ -f $(REMOTE_BASE_DIR)/.ports/$(PROJECT_NAME) ]; then \
		. $(REMOTE_BASE_DIR)/.ports/$(PROJECT_NAME) && \
		echo "  Web:     http://localhost:$$WEB_PORT" && \
		echo "  MySQL:   $$MYSQL_PORT" && \
		echo "  Redis:   $$REDIS_PORT"; \
	else \
		echo "  Web:     http://localhost:$(WEB_PORT)"; \
		echo "  MySQL:   $(MYSQL_PORT)"; \
		echo "  Redis:   $(REDIS_PORT)"; \
	fi

list-all:
	@./.protohost/lib/list_deployments.sh

nginx-config:
	@mkdir -p $(REMOTE_BASE_DIR)/.nginx
	@echo "Generating nginx config for $(PROJECT_NAME)..."
	@if [ ! -f $(REMOTE_BASE_DIR)/.ports/$(PROJECT_NAME) ]; then \
		echo "❌ Error: Deployment not running. Run 'make up' first."; \
		exit 1; \
	fi
	@. $(REMOTE_BASE_DIR)/.ports/$(PROJECT_NAME) && \
	echo "Using port: $$WEB_PORT" && \
	echo "server {" > $(REMOTE_BASE_DIR)/.nginx/$(PROJECT_NAME).conf
	@. $(REMOTE_BASE_DIR)/.ports/$(PROJECT_NAME) && \
	echo "    listen 443 ssl;" >> $(REMOTE_BASE_DIR)/.nginx/$(PROJECT_NAME).conf && \
	echo "    server_name $(PROJECT_NAME).$(REMOTE_HOST);" >> $(REMOTE_BASE_DIR)/.nginx/$(PROJECT_NAME).conf && \
	echo "" >> $(REMOTE_BASE_DIR)/.nginx/$(PROJECT_NAME).conf && \
	echo "    ssl_certificate /etc/letsencrypt/live/$(REMOTE_HOST)/fullchain.pem;" >> $(REMOTE_BASE_DIR)/.nginx/$(PROJECT_NAME).conf && \
	echo "    ssl_certificate_key /etc/letsencrypt/live/$(REMOTE_HOST)/privkey.pem;" >> $(REMOTE_BASE_DIR)/.nginx/$(PROJECT_NAME).conf && \
	echo "    include ssl-params.conf;" >> $(REMOTE_BASE_DIR)/.nginx/$(PROJECT_NAME).conf && \
	echo "" >> $(REMOTE_BASE_DIR)/.nginx/$(PROJECT_NAME).conf && \
	echo "    location / {" >> $(REMOTE_BASE_DIR)/.nginx/$(PROJECT_NAME).conf && \
	echo "        proxy_pass http://$(NGINX_PROXY_HOST):$$WEB_PORT;" >> $(REMOTE_BASE_DIR)/.nginx/$(PROJECT_NAME).conf && \
	echo "        proxy_http_version 1.1;" >> $(REMOTE_BASE_DIR)/.nginx/$(PROJECT_NAME).conf && \
	echo "        proxy_set_header Upgrade \$$http_upgrade;" >> $(REMOTE_BASE_DIR)/.nginx/$(PROJECT_NAME).conf && \
	echo "        proxy_set_header Connection \"upgrade\";" >> $(REMOTE_BASE_DIR)/.nginx/$(PROJECT_NAME).conf && \
	echo "        proxy_set_header Host \$$host;" >> $(REMOTE_BASE_DIR)/.nginx/$(PROJECT_NAME).conf && \
	echo "        proxy_set_header X-Real-IP \$$remote_addr;" >> $(REMOTE_BASE_DIR)/.nginx/$(PROJECT_NAME).conf && \
	echo "        proxy_set_header X-Forwarded-For \$$proxy_add_x_forwarded_for;" >> $(REMOTE_BASE_DIR)/.nginx/$(PROJECT_NAME).conf && \
	echo "        proxy_set_header X-Forwarded-Proto \$$scheme;" >> $(REMOTE_BASE_DIR)/.nginx/$(PROJECT_NAME).conf && \
	echo "        proxy_read_timeout 86400;" >> $(REMOTE_BASE_DIR)/.nginx/$(PROJECT_NAME).conf && \
	echo "        proxy_buffering off;" >> $(REMOTE_BASE_DIR)/.nginx/$(PROJECT_NAME).conf && \
	echo "    }" >> $(REMOTE_BASE_DIR)/.nginx/$(PROJECT_NAME).conf && \
	echo "}" >> $(REMOTE_BASE_DIR)/.nginx/$(PROJECT_NAME).conf && \
	echo "Nginx config written to $(REMOTE_BASE_DIR)/.nginx/$(PROJECT_NAME).conf" && \
	echo "  URL: https://$(PROJECT_NAME).$(REMOTE_HOST)" && \
	echo "  Port: $$WEB_PORT" && \
	echo "Deploying to nginx server..." && \
	scp $(REMOTE_BASE_DIR)/.nginx/$(PROJECT_NAME).conf $(NGINX_SERVER):/tmp/protohost-$(PROJECT_NAME).conf && \
	ssh $(NGINX_SERVER) "sudo mv /tmp/protohost-$(PROJECT_NAME).conf /etc/nginx/sites-enabled/protohost-$(PROJECT_NAME).conf && sudo service nginx restart" && \
	echo "✓ Nginx config deployed and nginx restarted"

nginx-enable:
	@./.protohost/lib/nginx_manage.sh enable $(PROJECT_NAME)

nginx-disable:
	@./.protohost/lib/nginx_manage.sh disable $(PROJECT_NAME)

nginx-list:
	@./.protohost/lib/nginx_manage.sh list

deploy:
	@echo "Deploying to $(or $(HOST),$(REMOTE_HOST))..."
	@./.protohost/lib/deploy.sh $(if $(RESET_DB),--reset-db) $(if $(NUKE),--nuke) $(if $(HOST),--host $(HOST))
EOF

echo "✓ Created .protohost/Makefile.inc"

# Add .protohost to .gitignore if not already there
if [ -f ".gitignore" ]; then
    if ! grep -q "^\.protohost/" .gitignore; then
        echo "📝 Adding .protohost/ to .gitignore..."
        echo "" >> .gitignore
        echo "# Protohost deploy (keep config, ignore cached scripts)" >> .gitignore
        echo ".protohost/" >> .gitignore
        echo "✓ Updated .gitignore"
    else
        echo "✓ .gitignore already has .protohost/"
    fi
else
    echo "📝 Creating .gitignore..."
    cat > .gitignore <<EOF
# Protohost deploy (keep config, ignore cached scripts)
.protohost/
EOF
    echo "✓ Created .gitignore"
fi

# Check if .protohost.config should be in .gitignore
echo ""
echo "⚠️  Important: .protohost.config contains project-specific settings."
echo "   You may want to:"
echo "   1. Commit it if settings are the same for all developers"
echo "   2. Add to .gitignore and create .protohost.config.example for reference"
echo ""

# Create hooks directory
mkdir -p .protohost/hooks
cat > .protohost/hooks/README.md <<EOF
# Protohost Deploy Hooks

Add custom scripts here to customize deployment behavior:

- \`pre-deploy.sh\` - Runs before deployment starts
- \`post-deploy.sh\` - Runs after successful deployment
- \`post-start.sh\` - Runs after containers start

Example post-start.sh:
\`\`\`bash
#!/bin/bash
# Generate sample data after containers start
docker compose -p \$PROJECT_NAME exec web python scripts/generate_data.py
\`\`\`

Make sure to chmod +x your hook scripts!
EOF

echo "✅ Installation complete!"
echo ""
echo "Next steps:"
echo "  1. Review and update .protohost.config"
echo "  2. Ensure your docker-compose.yml uses \${WEB_PORT:-3000} style port vars"
echo "  3. Run 'make up' to test locally"
echo "  4. Run 'make deploy' to deploy to protohost"
echo ""
echo "Documentation: $SCRIPT_DIR/README.md"
