#!/bin/bash
set -e

# Protohost Deploy - Installation Script
# This script sets up protohost-deploy in an existing project

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_DIR="${1:-.}"
PROTOHOST_LIB="${HOME}/.local/share/protohost-deploy"

echo "🚀 Installing protohost-deploy..."
echo ""

# Check if global installation exists
if [ ! -d "$PROTOHOST_LIB" ]; then
    echo "❌ Error: Protohost not installed globally"
    echo "   Run './global-install.sh' first to install protohost system-wide"
    exit 1
fi

# Ensure we're in a valid project directory
if [ ! -d "$PROJECT_DIR" ]; then
    echo "❌ Error: Directory '$PROJECT_DIR' does not exist"
    exit 1
fi

cd "$PROJECT_DIR"
PROJECT_DIR="$(pwd)"

echo "📁 Project directory: $PROJECT_DIR"
echo "📍 Using protohost from: $PROTOHOST_LIB"
echo ""

# Check for docker-compose.yml
if [ ! -f "docker-compose.yml" ]; then
    echo "⚠️  Warning: No docker-compose.yml found in project root"
    read -p "Continue anyway? (y/n) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

# Create .protohost directory
echo "📦 Creating .protohost directory..."
mkdir -p .protohost

# Create .protohost.config if it doesn't exist
if [ ! -f ".protohost.config" ]; then
    echo "⚙️  Creating .protohost.config..."

    # Try to detect git remote URL
    DETECTED_REPO_URL=""
    if [ -d ".git" ]; then
        DETECTED_REPO_URL=$(git config --get remote.origin.url 2>/dev/null || echo "")
    fi

    # Detect current git branch
    DETECTED_BRANCH="main"
    if [ -d ".git" ]; then
        DETECTED_BRANCH=$(git branch --show-current 2>/dev/null || echo "main")
    fi

    # Try to infer project name from directory
    PROJECT_NAME=$(basename "$PROJECT_DIR" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g')

    cat > .protohost.config <<EOF
# Protohost Deploy Configuration
# Generated by install.sh on $(date)

# Remote server configuration
REMOTE_HOST="protohost.xyz"
REMOTE_USER="\${USER}"
REMOTE_BASE_DIR="~/protohost"

# Network configuration
# NGINX_PROXY_HOST: IP address where Docker containers are running
# NGINX_SERVER: IP address where nginx is running (can be same or different)
NGINX_PROXY_HOST="10.10.20.4"
NGINX_SERVER="10.10.20.10"

# Project configuration
PROJECT_PREFIX="$PROJECT_NAME"

# Git repository
REPO_URL="${DETECTED_REPO_URL:-git@github.com:thatjpcsguy/protohost.git}"

# Deployment settings
TTL_DAYS=7  # Days until deployment auto-expires

# Optional: Custom port ranges (defaults shown)
# BASE_WEB_PORT=3000
# BASE_MYSQL_PORT=3306
# BASE_REDIS_PORT=6379
EOF

    echo "✓ Created .protohost.config"
    echo ""
    echo "⚠️  Please review and update .protohost.config with your settings:"
    echo "   - REMOTE_HOST: Your protohost server hostname"
    echo "   - REMOTE_USER: Your SSH username"
    echo "   - NGINX_PROXY_HOST: IP where Docker is running"
    echo "   - NGINX_SERVER: IP where nginx is running"
    echo "   - PROJECT_PREFIX: Short name for your project"
    echo "   - REPO_URL: Your git repository URL"
    echo ""
else
    echo "✓ .protohost.config already exists (keeping existing)"
fi

# Add protohost targets to Makefile or create one
if [ -f "Makefile" ]; then
    # Check if protohost targets already exist (check for actual include statement)
    if grep -q "include .protohost/Makefile.inc" Makefile; then
        echo "✓ Makefile already has protohost targets"
    else
        echo "📝 Adding protohost targets to existing Makefile..."
        cat >> Makefile <<'EOF'

# PROTOHOST-DEPLOY-TARGETS
# Auto-generated by protohost-deploy - do not edit this section manually
include .protohost/Makefile.inc
EOF
        echo "✓ Updated Makefile"
    fi
else
    echo "📝 Creating new Makefile with protohost targets..."
    cp "$SCRIPT_DIR/templates/Makefile.template" Makefile
    echo "✓ Created Makefile"
fi

# Copy Makefile.inc from global installation
echo "📄 Copying Makefile.inc from global installation..."
cp "$PROTOHOST_LIB/templates/Makefile.inc" .protohost/Makefile.inc
echo "✓ Created .protohost/Makefile.inc"

# Add .protohost.config.local to .gitignore
if [ -f ".gitignore" ]; then
    if ! grep -q "^\.protohost\.config\.local$" .gitignore; then
        echo "📝 Adding .protohost.config.local to .gitignore..."
        echo "" >> .gitignore
        echo "# Protohost deploy - only ignore local overrides" >> .gitignore
        echo ".protohost.config.local" >> .gitignore
        echo "✓ Updated .gitignore"
    else
        echo "✓ .gitignore already configured for protohost"
    fi
else
    echo "📝 Creating .gitignore..."
    cat > .gitignore <<EOF
# Protohost deploy - only ignore local overrides
.protohost.config.local
EOF
    echo "✓ Created .gitignore"
fi

# Show configuration pattern
echo ""
echo "💡 Configuration pattern:"
echo "   .protohost.config         - Project config (commit this)"
echo "   .protohost.config.local   - Local overrides (gitignored)"
echo "   .protohost/Makefile.inc   - Generated file (commit this)"
echo ""

# Create hooks directory
mkdir -p .protohost/hooks
cat > .protohost/hooks/README.md <<EOF
# Protohost Deploy Hooks

Add custom scripts here to customize deployment behavior:

- \`pre-deploy.sh\` - Runs before deployment starts
- \`post-deploy.sh\` - Runs after successful deployment
- \`post-start.sh\` - Runs after containers start

Example post-start.sh:
\`\`\`bash
#!/bin/bash
# Generate sample data after containers start
docker compose -p \$PROJECT_NAME exec web python scripts/generate_data.py
\`\`\`

Make sure to chmod +x your hook scripts!
EOF

echo "✅ Installation complete!"
echo ""
echo "Next steps:"
echo "  1. Review and update .protohost.config"
echo "  2. Ensure your docker-compose.yml uses \${WEB_PORT:-3000} style port vars"
echo "  3. Run 'make up' to test locally"
echo "  4. Run 'make deploy' to deploy to protohost"
echo ""
echo "Documentation: $SCRIPT_DIR/README.md"
